version: "3"
# I used the following Howto as the basis
# https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-16-04
networks:
  proxy:
    external: true
  internal:
    external: false
    
services:
  traefik:
    image: traefik:v2.0
    command: 
      - "--providers.docker=true"
    container_name: traefik
    hostname: traefik
    labels:
      - traefik.frontend.rule=Host:lb-monitor.becheftigt.de
      - traefik.port=8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443

  nextcloud:
    image: nextcloud
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
    links:
      - mysql
    restart: always
    volumes:
      - ./nextcloud-core:/var/www/html
      - ./nextcloud-apps:/var/www/html/custom_apps
      - ./nextcloud-data:/var/www/html/data
      - ./nextcloud-config:/var/www/html/config
    labels:
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:next.becheftigt.de
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:
    restart: always
    volumes:
      - ./nextcloud-mysql:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false
 
  adminer:
    image: adminer:4.3.1-standalone
    labels:
      - traefik.backend=adminer
      - traefik.frontend.rule=Host:db-admin.becheftigt.de
      - traefik.docker.network=proxy
      - traefik.port=8080
    networks:
      - internal
      - proxy
    depends_on:
      - mysql